### ISSUE TITLE
Inline JS

### ISSUE THREAD

**Issue by mrcwinn** [Rewinn/Arcade-League#1]
https://github.com/Rewinn/Arcade-League/blob/master/index.html#L385

Let's get all that inline JS out of the HTML page and into a separate file.

**Comment by Rewinn** [comment]
I added the inline JS to the bootstrap.js file.

**Comment by mrcwinn** [comment]
Re-opening! I don't see a commit in the log. No commit, no credit!

**Comment by mrcwinn** [comment]
@Rewinn can't close this ticket quite yet! I see you removed the custom JS (starting with `CUSTOM THEME`) — but you tacked it in to `bootstrap.js`. That file is an external library provided by the Bootstrap team. You should *never* modify an external dependency directly. No exceptions. What happens if you need to update `bootstrap.js` to a newer version, but forget to protect the custom code? You'll inadvertently remove functionality.

You should have three files:

`jquery.js` (provided by jQuery)

`bootstrap.js` (provided by Bootstrap)

`main.js` (a file of your own, containing JS *unique to your project*)
