### ISSUE TITLE
Remove unused CSS

### ISSUE THREAD

**Issue by mrcwinn** [Rewinn/Arcade-League#4]
You're linking to a minified version of `bootstrap.css`, but you have both files. Consider either linking to the unminified version of Bootstrap and deleting `bootstrap.min.css` or sticking with what you've got and removing `bootstrap.css`.

The point is: don't get in the bad habit of throwing in unused files.

**Comment by Rewinn** [comment]
I LOVE ALL THESE TIPS!!! THANKS!!!!!
